-- Tabla principal para los resultados del Quiz de Autocompasión
CREATE TABLE QuizAutocompasion (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_name text,
  total_score integer not null,
  time_taken_seconds integer,
  q1 integer,
  q2 integer,
  q3 integer,
  q4 integer,
  q5 integer,
  q6 integer,
  q7 integer,
  q8 integer,
  q9 integer,
  q10 integer,
  q11 integer,
  q12 integer
);

-- Habilitar Políticas de Seguridad de Base de Datos (RLS)
ALTER TABLE QuizAutocompasion ENABLE ROW LEVEL SECURITY;

-- Crear política para permitir la inserción a usuarios anónimos (ya que el quiz es abierto)
CREATE POLICY "Permitir inserción pública" 
ON QuizAutocompasion 
FOR INSERT 
TO public
WITH CHECK (true);

-- (Opcional) Crear política para lectura si necesitas mostrar estadísticas públicas después
CREATE POLICY "Permitir lectura pública" 
ON QuizAutocompasion 
FOR SELECT 
TO public
USING (true);
